//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMENAZAS
    {
        public int ID_AMENAZA { get; set; }
        public string AM_NOMBRE { get; set; }
        public string AM_DESCRIPCION { get; set; }
        public Nullable<System.DateTime> AM_FECHA_CREACION { get; set; }
    }
}
