//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESCALA_FRECUENCIA
    {
        public int ID_ESCALA_FRECUENCIA { get; set; }
        public string E_F_NOMBRE { get; set; }
        public string E_F_DESCRIPCION { get; set; }
        public Nullable<System.DateTime> E_F_FECHA_CREACION { get; set; }
        public string E_F_VALOR_LETRA { get; set; }
        public Nullable<decimal> E_F_VALOR { get; set; }
    }
}
