//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAPA_CALOR
    {
        public int ID_MAPA_CALOR { get; set; }
        public Nullable<int> ID_ESCALA_FRECUENCIA { get; set; }
        public Nullable<decimal> PROMEDIO_IMPACTO_DESDE { get; set; }
        public Nullable<decimal> PROMEDIO_IMPACTO_HASTA { get; set; }
        public Nullable<decimal> RIESGO_DESDE { get; set; }
        public Nullable<decimal> RIESGO_HASTA { get; set; }
        public string COLOR { get; set; }
    }
}
