//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RIESGO_TOTAL_Entities : DbContext
    {
        public RIESGO_TOTAL_Entities()
            : base("name=RIESGO_TOTAL_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACTIVO> ACTIVO { get; set; }
        public virtual DbSet<ACTIVO_VULNERABILIDAD> ACTIVO_VULNERABILIDAD { get; set; }
        public virtual DbSet<AMENAZAS> AMENAZAS { get; set; }
        public virtual DbSet<ELEMENTOS_DEGRADACION> ELEMENTOS_DEGRADACION { get; set; }
        public virtual DbSet<ESCALA_DEGRADACION> ESCALA_DEGRADACION { get; set; }
        public virtual DbSet<ESCALA_FRECUENCIA> ESCALA_FRECUENCIA { get; set; }
        public virtual DbSet<GRUPO_ACTIVOS> GRUPO_ACTIVOS { get; set; }
        public virtual DbSet<MAPA_CALOR> MAPA_CALOR { get; set; }
        public virtual DbSet<VULNERABILIDADES> VULNERABILIDADES { get; set; }
        public virtual DbSet<VULNERABILIDADES_AMENAZAS> VULNERABILIDADES_AMENAZAS { get; set; }
    }
}
