//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VULNERABILIDADES_AMENAZAS
    {
        public int ID_AMENAZA { get; set; }
        public int ID_VULNERABILIDAD { get; set; }
        public int ID_VULNERABILIDADES_AMENAZAS { get; set; }
    }
}
